# Generated by Django 3.1.4 on 2020-12-17 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Derivation',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=184)),
                ('wweia_cat_num', models.PositiveSmallIntegerField()),
                ('wweia_cat_desc', models.CharField(max_length=48)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_num', models.PositiveSmallIntegerField()),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=134)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=8)),
                ('measure', models.CharField(max_length=3)),
                ('retention', models.PositiveSmallIntegerField()),
                ('weight', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='fndds.food')),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('tag', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=7)),
                ('decimals', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Portion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=114)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subcode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_num', models.PositiveSmallIntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_weights', to='fndds.food')),
                ('portion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portion_weights', to='fndds.portion')),
                ('subcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fndds.subcode')),
            ],
        ),
        migrations.CreateModel(
            name='NutrientValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_values', to='fndds.food')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fndds.nutrient')),
            ],
        ),
        migrations.CreateModel(
            name='Moisture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.SmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fndds.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='portion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='fndds.portion'),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_num', models.PositiveSmallIntegerField()),
                ('desc', models.CharField(max_length=80)),
                ('wweia_cat_desc', models.CharField(max_length=48)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='fndds.food')),
            ],
        ),
    ]
