# Generated by Django 3.1.4 on 2020-12-17 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fndds', '0001_initial'),
        ('t1d', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t1dfood',
            name='returned_serving',
        ),
        migrations.RemoveField(
            model_name='t1dfood',
            name='servingSize',
        ),
        migrations.RemoveField(
            model_name='t1dfood',
            name='taken_serving',
        ),
        migrations.CreateModel(
            name='T1DServing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_serving', models.FloatField(blank=True, null=True)),
                ('returned_serving', models.FloatField(blank=True, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t1d.t1dfood')),
                ('servingSize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t1ds_portion_sizes', to='fndds.weight')),
            ],
        ),
    ]
